services:
  - type: web
    name: swipesound
    runtime: node
    buildCommand: npm install --prefix server && cd client && npm install --legacy-peer-deps && npm run build
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
